In [1]:
import glob
import pandas as pd

In [2]:
review = pd.DataFrame(pd.read_csv("reviews.csv"))
ingredients = pd.DataFrame(pd.read_csv("Ingredient.csv"))
minmax = pd.DataFrame(pd.read_csv("MinMax.csv"))
times = pd.DataFrame(pd.read_csv("TimeFormat.csv"))
recipes = pd.DataFrame(pd.read_csv("recipes.csv"))

In [3]:
review.shape

(271678, 2)

In [4]:
ingredients.head()

   Unnamed: 0  RecipeId  IngredientsCount
0           0        38                 4
1           1        39                25
2           2        40                 7
3           3        41                14
4           4        42                 5

In [5]:
#removing Unnamed:0 coluns form the ingredients
ingredients = ingredients[["RecipeId", "IngredientsCount"]]

In [6]:
ingredients.head()

   RecipeId  IngredientsCount
0        38                 4
1        39                25
2        40                 7
3        41                14
4        42                 5

In [7]:
times.head()

   Unnamed: 0  RecipeId  CookTime  PrepTime  TotalTime
0           0        38      1440        45       1485
1           1        39        25       240        265
2           2        40         5        30         35
3           3        41        20      1440       1460
4           4        42        30        20         50

In [8]:
times = times[["RecipeId", "CookTime", "PrepTime", "TotalTime"]]

In [9]:
times.head()

   RecipeId  CookTime  PrepTime  TotalTime
0        38      1440        45       1485
1        39        25       240        265
2        40         5        30         35
3        41        20      1440       1460
4        42        30        20         50

In [10]:
minmax.head()

   RecipeId  min  max      mean
0        38    4    5  4.250000
1        39    3    3  3.000000
2        40    1    5  4.333333
3        41    4    5  4.500000
4        42    0    5  2.666667

In [11]:
review.head()

   RecipeId Review_Class
0        38      average
1        39      average
2        40      average
3        41         good
4        42      average

##### We found that all the dataset have a common primary key. That is recipeId. 
##### We will add all the dataset with recipe (main dataset) on recipeID

In [12]:
recipes.head()

,RecipeId,Name,AuthorId,AuthorName,CookTime,PrepTime,TotalTime,DatePublished,Description,Images,...,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions
0,38,Low-Fat Berry Blue Frozen Dessert,1533,Dancer,PT24H,PT45M,PT24H45M,1999-08-09T21:46:00Z,Make and share this Low-Fat Berry Blue Frozen ...,"c(""https://img.sndimg.com/food/image/upload/w_...",...,1.3,8.0,29.8,37.1,3.6,30.2,3.2,4.0,NaN,"c(""Toss 2 cups berries with sugar."", ""Let stan..."
1,39,Biryani,1567,elly9812,PT25M,PT4H,PT4H25M,1999-08-29T13:12:00Z,Make and share this Biryani recipe from Food.com.,"c(""https://img.sndimg.com/food/image/upload/w_...",...,16.6,372.8,368.4,84.4,9.0,20.4,63.4,6.0,NaN,"c(""Soak saffron in warm milk for 5 minutes and..."
2,40,Best Lemonade,1566,Stephen Little,PT5M,PT30M,PT35M,1999-09-05T19:52:00Z,This is from one of my first Good House Keepi...,"c(""https://img.sndimg.com/food/image/upload/w_...",...,0.0,0.0,1.8,81.5,0.4,77.2,0.3,4.0,NaN,"c(""Into a 1 quart Jar with tight fitting lid, ..."
3,41,Carina's Tofu-Vegetable Kebabs,1586,Cyclopz,PT20M,PT24H,PT24H20M,1999-09-03T14:54:00Z,This dish is best prepared a day in advance to...,"c(""https://img.sndimg.com/food/image/upload/w_...",...,3.8,0.0,1558.6,64.2,17.3,32.1,29.3,2.0,4 kebabs,"c(""Drain the tofu, carefully squeezing out exc..."
4,42,Cabbage Soup,1538,Duckie067,PT30M,PT20M,PT50M,1999-09-19T06:19:00Z,Make and share this Cabbage Soup recipe from F...,"""https://img.sndimg.com/food/image/upload/w_55...",...,0.1,0.0,959.3,25.1,4.8,17.7,4.3,4.0,NaN,"c(""Mix everything together and bring to a boil..."

In [13]:
recipes.columns

Index(['RecipeId', 'Name', 'AuthorId', 'AuthorName', 'CookTime', 'PrepTime',
       'TotalTime', 'DatePublished', 'Description', 'Images', 'RecipeCategory',
       'Keywords', 'RecipeIngredientQuantities', 'RecipeIngredientParts',
       'AggregatedRating', 'ReviewCount', 'Calories', 'FatContent',
       'SaturatedFatContent', 'CholesterolContent', 'SodiumContent',
       'CarbohydrateContent', 'FiberContent', 'SugarContent', 'ProteinContent',
       'RecipeServings', 'RecipeYield', 'RecipeInstructions'],
      dtype='object')

##### No we will keep all the columns that are necessary for our analysis
##### And remove the columns that we will get from other dataset

In [14]:
type(recipes)

pandas.core.frame.DataFrame

In [15]:
recipes = recipes[['RecipeId', 'Name','Images', 'RecipeCategory',
        'AggregatedRating', 'ReviewCount', 'Calories', 'FatContent',
       'SaturatedFatContent', 'CholesterolContent', 'SodiumContent',
       'CarbohydrateContent', 'FiberContent', 'SugarContent', 'ProteinContent',
       'RecipeServings']]

In [16]:
type(recipes)

pandas.core.frame.DataFrame

In [17]:
recipes.head()

,RecipeId,Name,Images,RecipeCategory,AggregatedRating,ReviewCount,Calories,FatContent,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings
0,38,Low-Fat Berry Blue Frozen Dessert,"c(""https://img.sndimg.com/food/image/upload/w_...",Frozen Desserts,4.5,4.0,170.9,2.5,1.3,8.0,29.8,37.1,3.6,30.2,3.2,4.0
1,39,Biryani,"c(""https://img.sndimg.com/food/image/upload/w_...",Chicken Breast,3.0,1.0,1110.7,58.8,16.6,372.8,368.4,84.4,9.0,20.4,63.4,6.0
2,40,Best Lemonade,"c(""https://img.sndimg.com/food/image/upload/w_...",Beverages,4.5,10.0,311.1,0.2,0.0,0.0,1.8,81.5,0.4,77.2,0.3,4.0
3,41,Carina's Tofu-Vegetable Kebabs,"c(""https://img.sndimg.com/food/image/upload/w_...",Soy/Tofu,4.5,2.0,536.1,24.0,3.8,0.0,1558.6,64.2,17.3,32.1,29.3,2.0
4,42,Cabbage Soup,"""https://img.sndimg.com/food/image/upload/w_55...",Vegetable,4.5,11.0,103.6,0.4,0.1,0.0,959.3,25.1,4.8,17.7,4.3,4.0

In [18]:
recipes.shape

(522517, 16)

In [19]:
time_merged_data = recipes.merge(times, on = ["RecipeId"])
# not specifing the merge type always do a inner join

In [20]:
time_merged_data.shape

(522517, 19)

In [21]:
review_merged_data = time_merged_data.merge(review, on = ["RecipeId"], how = "left")

In [22]:
review_merged_data.shape

(522517, 20)

In [23]:
review_merged_data.head()

,RecipeId,Name,Images,RecipeCategory,AggregatedRating,ReviewCount,Calories,FatContent,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings,CookTime,PrepTime,TotalTime,Review_Class
0,38,Low-Fat Berry Blue Frozen Dessert,"c(""https://img.sndimg.com/food/image/upload/w_...",Frozen Desserts,4.5,4.0,170.9,2.5,1.3,8.0,29.8,37.1,3.6,30.2,3.2,4.0,1440,45,1485,average
1,39,Biryani,"c(""https://img.sndimg.com/food/image/upload/w_...",Chicken Breast,3.0,1.0,1110.7,58.8,16.6,372.8,368.4,84.4,9.0,20.4,63.4,6.0,25,240,265,average
2,40,Best Lemonade,"c(""https://img.sndimg.com/food/image/upload/w_...",Beverages,4.5,10.0,311.1,0.2,0.0,0.0,1.8,81.5,0.4,77.2,0.3,4.0,5,30,35,average
3,41,Carina's Tofu-Vegetable Kebabs,"c(""https://img.sndimg.com/food/image/upload/w_...",Soy/Tofu,4.5,2.0,536.1,24.0,3.8,0.0,1558.6,64.2,17.3,32.1,29.3,2.0,20,1440,1460,good
4,42,Cabbage Soup,"""https://img.sndimg.com/food/image/upload/w_55...",Vegetable,4.5,11.0,103.6,0.4,0.1,0.0,959.3,25.1,4.8,17.7,4.3,4.0,30,20,50,average

In [24]:
ingredients_merged_data =  review_merged_data.merge(ingredients, on = ["RecipeId"])
#this one will be an inner join as indgredints.csv made form recipes dataset itself

In [25]:
ingredients_merged_data.shape

(522517, 21)

In [26]:
minmax.shape

(271678, 4)

In [27]:
main_dataset = ingredients_merged_data.merge(minmax, on = ["RecipeId"], how = "left")

In [28]:
main_dataset.shape

main_dataset = main_dataset.rename(columns = {"min":"minimum_rating", "max":"maximum_rating", "mean":"mean_of_rating"})

In [29]:
main_dataset.to_csv("main_data.csv")

In [30]:
main_dataset.head(5)

,RecipeId,Name,Images,RecipeCategory,AggregatedRating,ReviewCount,Calories,FatContent,SaturatedFatContent,CholesterolContent,...,ProteinContent,RecipeServings,CookTime,PrepTime,TotalTime,Review_Class,IngredientsCount,minimum_rating,maximum_rating,mean_of_rating
0,38,Low-Fat Berry Blue Frozen Dessert,"c(""https://img.sndimg.com/food/image/upload/w_...",Frozen Desserts,4.5,4.0,170.9,2.5,1.3,8.0,...,3.2,4.0,1440,45,1485,average,4,4.0,5.0,4.250000
1,39,Biryani,"c(""https://img.sndimg.com/food/image/upload/w_...",Chicken Breast,3.0,1.0,1110.7,58.8,16.6,372.8,...,63.4,6.0,25,240,265,average,25,3.0,3.0,3.000000
2,40,Best Lemonade,"c(""https://img.sndimg.com/food/image/upload/w_...",Beverages,4.5,10.0,311.1,0.2,0.0,0.0,...,0.3,4.0,5,30,35,average,7,1.0,5.0,4.333333
3,41,Carina's Tofu-Vegetable Kebabs,"c(""https://img.sndimg.com/food/image/upload/w_...",Soy/Tofu,4.5,2.0,536.1,24.0,3.8,0.0,...,29.3,2.0,20,1440,1460,good,14,4.0,5.0,4.500000
4,42,Cabbage Soup,"""https://img.sndimg.com/food/image/upload/w_55...",Vegetable,4.5,11.0,103.6,0.4,0.1,0.0,...,4.3,4.0,30,20,50,average,5,0.0,5.0,2.666667