In [17]:
# Import required libraries
import pandas as pd
import re

# Load recipes data into a variable called recipes
recipes = pd.DataFrame(pd.read_csv("C:/Users/SLL26/Desktop/Data Science and Analytics/CS5706 MACHINE LEARNING/CS5811 Coursework/recipes.csv"))

# View top 3 values from the loaded dataset
recipes.head(3)

,RecipeId,Name,AuthorId,AuthorName,CookTime,PrepTime,TotalTime,DatePublished,Description,Images,...,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions
0,38,Low-Fat Berry Blue Frozen Dessert,1533,Dancer,PT24H,PT45M,PT24H45M,1999-08-09T21:46:00Z,Make and share this Low-Fat Berry Blue Frozen ...,"c(""https://img.sndimg.com/food/image/upload/w_...",...,1.3,8.0,29.8,37.1,3.6,30.2,3.2,4.0,NaN,"c(""Toss 2 cups berries with sugar."", ""Let stan..."
1,39,Biryani,1567,elly9812,PT25M,PT4H,PT4H25M,1999-08-29T13:12:00Z,Make and share this Biryani recipe from Food.com.,"c(""https://img.sndimg.com/food/image/upload/w_...",...,16.6,372.8,368.4,84.4,9.0,20.4,63.4,6.0,NaN,"c(""Soak saffron in warm milk for 5 minutes and..."
2,40,Best Lemonade,1566,Stephen Little,PT5M,PT30M,PT35M,1999-09-05T19:52:00Z,This is from one of my first Good House Keepi...,"c(""https://img.sndimg.com/food/image/upload/w_...",...,0.0,0.0,1.8,81.5,0.4,77.2,0.3,4.0,NaN,"c(""Into a 1 quart Jar with tight fitting lid, ..."

In [18]:
# We can import a package from GitHub whic does exactly what we need, but i will build a new logic.
# URL : https://github.com/metomi/isodatetime
import metomi.isodatetime.parsers as parse
duration = parse.DurationParser().parse('PT1H30M')
duration.get_days_and_seconds()

(0.0, 5400.0)

In [19]:

# Create a User Defined Function to convert ISO duration i.e PT3H40M into seconds.
# The function below removes PT from each observation and splits string based on keywords ("H", "M", "S") and converts in seconds

def time(var):
    time = 0
    text = str(var)
    # Remove PT from each observation
    text = text.replace("PT", "")
    # Checks the format and converts accordingly
    if text == 'nan':
        time = 0
    elif ('S' in text):
        time = 0
    elif ('H' in text) and ('M' in text):
        time = time + int(text.split('H')[0])*60 + int(text.split('H')[1].replace('M', ''))
    elif 'H' in text:
        time = time + int(text.replace('H', ''))*60
    elif 'M' in text:
        time = time + int(text.replace('M', ''))
    else:
        time = 'NA'
    return time

# Apply the function to all three columns related to duration
recipes["CookTime"] = recipes["CookTime"].apply(time)
recipes["PrepTime"] = recipes["PrepTime"].apply(time)
recipes["TotalTime"] = recipes["TotalTime"].apply(time)

In [6]:
recipes.head()

,RecipeId,Name,AuthorId,AuthorName,CookTime,PrepTime,TotalTime,DatePublished,Description,Images,...,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions
0,38,Low-Fat Berry Blue Frozen Dessert,1533,Dancer,1440,45,1485,1999-08-09T21:46:00Z,Make and share this Low-Fat Berry Blue Frozen ...,"c(""https://img.sndimg.com/food/image/upload/w_...",...,1.3,8.0,29.8,37.1,3.6,30.2,3.2,4.0,NaN,"c(""Toss 2 cups berries with sugar."", ""Let stan..."
1,39,Biryani,1567,elly9812,25,240,265,1999-08-29T13:12:00Z,Make and share this Biryani recipe from Food.com.,"c(""https://img.sndimg.com/food/image/upload/w_...",...,16.6,372.8,368.4,84.4,9.0,20.4,63.4,6.0,NaN,"c(""Soak saffron in warm milk for 5 minutes and..."
2,40,Best Lemonade,1566,Stephen Little,5,30,35,1999-09-05T19:52:00Z,This is from one of my first Good House Keepi...,"c(""https://img.sndimg.com/food/image/upload/w_...",...,0.0,0.0,1.8,81.5,0.4,77.2,0.3,4.0,NaN,"c(""Into a 1 quart Jar with tight fitting lid, ..."
3,41,Carina's Tofu-Vegetable Kebabs,1586,Cyclopz,20,1440,1460,1999-09-03T14:54:00Z,This dish is best prepared a day in advance to...,"c(""https://img.sndimg.com/food/image/upload/w_...",...,3.8,0.0,1558.6,64.2,17.3,32.1,29.3,2.0,4 kebabs,"c(""Drain the tofu, carefully squeezing out exc..."
4,42,Cabbage Soup,1538,Duckie067,30,20,50,1999-09-19T06:19:00Z,Make and share this Cabbage Soup recipe from F...,"""https://img.sndimg.com/food/image/upload/w_55...",...,0.1,0.0,959.3,25.1,4.8,17.7,4.3,4.0,NaN,"c(""Mix everything together and bring to a boil..."

In [20]:
# Import required libraries
#!pip install textblob
import glob
import re
import pandas as pd
from textblob import TextBlob

In [21]:
glob.glob("C:/Users/SLL26/Desktop/Data Science and Analytics/CS5706 MACHINE LEARNING/CS5811 Coursework/reviews.csv")

['C:/Users/SLL26/Desktop/Data Science and Analytics/CS5706 MACHINE LEARNING/CS5811 Coursework/reviews.csv']

In [22]:
reviews = pd.read_csv("C:/Users/SLL26/Desktop/Data Science and Analytics/CS5706 MACHINE LEARNING/CS5811 Coursework/reviews.csv")

In [25]:
# User Defined Function to check the review text and convert it into a likert scale
# Likert Scale: very poor, poor, average, good, very good. Based on polarity and sensitivity.
def sentiment(x):
        text = str(x)
        polarity = TextBlob(text).sentiment.polarity*100
        sensitivity = TextBlob(text).sentiment.subjectivity*100
    
        if sensitivity > 50:
            if polarity>=0:
                if polarity >=40 and polarity <80:
                    return "good"
                if polarity >=80 and polarity <=100:
                    return "very good"
                if polarity <=39:
                    return "average"

            if polarity<0:
                polarity = polarity * -1
                if polarity <=39:
                    return "average"
                if polarity >=40 and polarity <80:
                    return "poor"
                if polarity >=80 and polarity <=100:
                    return "very poor"
        else:
            return "average"

In [26]:
reviews.head()

,ReviewId,RecipeId,AuthorId,AuthorName,Rating,Review,DateSubmitted,DateModified
0,2,992,2008,gayg msft,5,better than any you can get at a restaurant!,2000-01-25T21:44:00Z,2000-01-25T21:44:00Z
1,7,4384,1634,Bill Hilbrich,4,"I cut back on the mayo, and made up the differ...",2001-10-17T16:49:59Z,2001-10-17T16:49:59Z
2,9,4523,2046,Gay Gilmore ckpt,2,i think i did something wrong because i could ...,2000-02-25T09:00:00Z,2000-02-25T09:00:00Z
3,13,7435,1773,Malarkey Test,5,easily the best i have ever had. juicy flavor...,2000-03-13T21:15:00Z,2000-03-13T21:15:00Z
4,14,44,2085,Tony Small,5,An excellent dish.,2000-03-28T12:51:00Z,2000-03-28T12:51:00Z

In [ ]:
reviews["Review"] = reviews["Review"].apply(sentiment)

In [35]:
reviews.head()

,ReviewId,RecipeId,AuthorId,AuthorName,Rating,Review,DateSubmitted,DateModified
0,2,992,2008,gayg msft,5,better than any you can get at a restaurant!,2000-01-25T21:44:00Z,2000-01-25T21:44:00Z
1,7,4384,1634,Bill Hilbrich,4,"I cut back on the mayo, and made up the differ...",2001-10-17T16:49:59Z,2001-10-17T16:49:59Z
2,9,4523,2046,Gay Gilmore ckpt,2,i think i did something wrong because i could ...,2000-02-25T09:00:00Z,2000-02-25T09:00:00Z
3,13,7435,1773,Malarkey Test,5,easily the best i have ever had. juicy flavor...,2000-03-13T21:15:00Z,2000-03-13T21:15:00Z
4,14,44,2085,Tony Small,5,An excellent dish.,2000-03-28T12:51:00Z,2000-03-28T12:51:00Z

In [27]:
# view top three observations of the column named RecipeIngredientParts
recipes['RecipeIngredientParts'].head(3)

0    c("blueberries", "granulated sugar", "vanilla ...
1    c("saffron", "milk", "hot green chili peppers"...
2    c("sugar", "lemons, rind of", "lemon, zest of"...
Name: RecipeIngredientParts, dtype: object

In [29]:
# splitting each ingredient which is a string, with comma, then counting the number of strings in each list
i = []
for value in recipes['RecipeIngredientParts']:
    words = value.split(',')
    i.append(len(words))
    
print(words)

['c("hard-boiled eggs"', ' "breakfast sausage"', ' "panko breadcrumbs"', ' "Worcestershire sauce"', ' "flour"', ' "panko breadcrumbs"', ' "water")']

In [31]:
# loading the count of strings in each list, creating a new column named IngredientsCount 
recipes['IngredientsCount'] = i

In [33]:
# view top three observations
recipes.head(3)

,RecipeId,Name,AuthorId,AuthorName,CookTime,PrepTime,TotalTime,DatePublished,Description,Images,...,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions,IngredientsCount
0,38,Low-Fat Berry Blue Frozen Dessert,1533,Dancer,1440,45,1485,1999-08-09T21:46:00Z,Make and share this Low-Fat Berry Blue Frozen ...,"c(""https://img.sndimg.com/food/image/upload/w_...",...,8.0,29.8,37.1,3.6,30.2,3.2,4.0,NaN,"c(""Toss 2 cups berries with sugar."", ""Let stan...",4
1,39,Biryani,1567,elly9812,25,240,265,1999-08-29T13:12:00Z,Make and share this Biryani recipe from Food.com.,"c(""https://img.sndimg.com/food/image/upload/w_...",...,372.8,368.4,84.4,9.0,20.4,63.4,6.0,NaN,"c(""Soak saffron in warm milk for 5 minutes and...",25
2,40,Best Lemonade,1566,Stephen Little,5,30,35,1999-09-05T19:52:00Z,This is from one of my first Good House Keepi...,"c(""https://img.sndimg.com/food/image/upload/w_...",...,0.0,1.8,81.5,0.4,77.2,0.3,4.0,NaN,"c(""Into a 1 quart Jar with tight fitting lid, ...",7

In [34]:
reviews = reviews[['RecipeId','Review','Review_classified']]

KeyError: "['Review_classified'] not in index"

In [ ]:
reviews.head()

In [ ]:
#A function that convert likert scale to some score
review_list = ["very poor", "poor", "average", "good", "very good"]
def review_score(x):
        if x == review_list[0]:
            return 1
        elif x == review_list[1]:
            return 2
        elif x == review_list[3]:
            return 4
        elif x == review_list[4]:
            return 5
        else:
            return 3

In [ ]:
# A function that convert score to likert scale string again
def review_class(x):
        if x >= 5:
            return review_list[4] 
        elif x >=4:
            return review_list[3]
        elif x >= 3:
            return review_list[2]
        elif x >= 2:
            return review_list[1]
        else:
            return review_list[0]

In [ ]:
reviews["Review_Score"] = reviews["Review_classified"].apply(review_score)
# converting likert scale strings into score for furhter operation

In [ ]:
group_data = reviews.groupby(['RecipeId'], as_index = False).sum()
#groupby data by unique recipies and the sum funciton for getting the total review score for a unique recipe
count_data = reviews.groupby(['RecipeId'], as_index = False).count()
#getting the count of review occurs for each recipie
#so that we can calcualte the average review score

In [ ]:
group_data.head()

In [ ]:
count_data = count_data[["RecipeId", "Review"]]
#selecting only the necessary columns

In [ ]:
count_data.head()

In [ ]:
reviews_score = group_data.merge(count_data,on='RecipeId')
#merge dataframe on RecipeId

In [ ]:
reviews_score.head()

In [ ]:
reviews_score["Average_Score"] = reviews_score["Review_Score"]/reviews_score["Review"]
#getting the average review score, which again will be converted to likert classes

In [ ]:
reviews_score.head()

In [ ]:
reviews_score["Review_Class"] = reviews_score["Average_Score"].apply(review_class)
#converting score to likert scale again

In [ ]:
dataframe.head()

In [ ]:
clean_data.to_csv("Reviews.csv", index = False)
#saving the data as a comma separated value file